/** ------------------------------------------------------------
  * A U T O   G E N E R A T E D
  * Generator: Rocs wgen (build Aug  3 2018 14:01:31)
  * Module: rocrail
  * Date: Fri Aug  3 14:01:35 2018
  */

#ifndef __WRAPPER_Loc_H
#define __WRAPPER_Loc_H

#include "rocrail/wrapper/public/wrapper.h"
#include "rocs/public/rocs.h"
#include "rocs/public/objbase.h"
#include "rocs/public/node.h"
#include "rocs/public/str.h"
#ifdef __cplusplus
  extern "C" {
#endif


struct __wLoc {
  const char* (*name)(void);
  const char* (*remark)(void);
  Boolean (*required)(void);
  const char* (*cardinality)(void);
  const char* V_mode_kmh;
  const char* V_mode_percent;
  const char* V_mode_step;
  const char* activate;
  const char* addblock2trip;
  const char* assigntrain;
  const char* bidikmh;
  const char* block;
  const char* blockside;
  const char* brake;
  const char* cargo_all;
  const char* cargo_cleaning;
  const char* cargo_goods;
  const char* cargo_ice;
  const char* cargo_light;
  const char* cargo_lightgoods;
  const char* cargo_mixed;
  const char* cargo_none;
  const char* cargo_person;
  const char* cargo_post;
  const char* cargo_regional;
  const char* cargo_shunting;
  const char* classadd;
  const char* classdel;
  const char* classset;
  const char* climb;
  const char* consist;
  const char* cruise;
  const char* deactivate;
  const char* direction;
  const char* dirfun;
  const char* discover;
  const char* dispatch;
  const char* engine_automobile;
  const char* engine_diesel;
  const char* engine_electric;
  const char* engine_steam;
  const char* fieldcmd;
  const char* function;
  const char* go;
  const char* gomanual;
  const char* gotoblock;
  const char* govirtual;
  const char* info;
  const char* manualoff;
  const char* manualon;
  const char* max;
  const char* mid;
  const char* min;
  const char* mode_auto;
  const char* mode_halfauto;
  const char* mode_idle;
  const char* mode_wait;
  const char* modereason_checkroute;
  const char* modereason_destfound;
  const char* modereason_initdest;
  const char* modereason_nodest;
  const char* modereason_unexpectedenter;
  const char* modereason_unexpectedexit;
  const char* modereason_unexpectedin;
  const char* modereason_waitforevent;
  const char* pomread;
  const char* pomwrite;
  const char* prot_A;
  const char* prot_C;
  const char* prot_F;
  const char* prot_L;
  const char* prot_M;
  const char* prot_N;
  const char* prot_P;
  const char* prot_S;
  const char* prot_X;
  const char* release;
  const char* releasetrain;
  const char* reset;
  const char* resetmanualmode;
  const char* setmanualmode;
  const char* shortid;
  const char* shuntingoff;
  const char* shuntingon;
  const char* softreset;
  const char* stop;
  const char* stopgo;
  const char* swap;
  const char* useschedule;
  const char* usetour;
  const char* velocity;
  int (*getV)(iONode);
  void (*setV)(iONode,int);
  int (*getV_Rcru)(iONode);
  void (*setV_Rcru)(iONode,int);
  int (*getV_Rmax)(iONode);
  void (*setV_Rmax)(iONode,int);
  int (*getV_Rmid)(iONode);
  void (*setV_Rmid)(iONode,int);
  int (*getV_Rmin)(iONode);
  void (*setV_Rmin)(iONode,int);
  int (*getV_cru)(iONode);
  void (*setV_cru)(iONode,int);
  const char* (*getV_hint)(iONode);
  void (*setV_hint)(iONode,const char*);
  int (*getV_max)(iONode);
  void (*setV_max)(iONode,int);
  int (*getV_maxkmh)(iONode);
  void (*setV_maxkmh)(iONode,int);
  int (*getV_maxsec)(iONode);
  void (*setV_maxsec)(iONode,int);
  int (*getV_mid)(iONode);
  void (*setV_mid)(iONode,int);
  int (*getV_min)(iONode);
  void (*setV_min)(iONode,int);
  const char* (*getV_mode)(iONode);
  void (*setV_mode)(iONode,const char*);
  int (*getV_raw)(iONode);
  void (*setV_raw)(iONode,int);
  int (*getV_rawMax)(iONode);
  void (*setV_rawMax)(iONode,int);
  int (*getV_realkmh)(iONode);
  void (*setV_realkmh)(iONode,int);
  int (*getV_step)(iONode);
  void (*setV_step)(iONode,int);
  int (*getaccelmax)(iONode);
  void (*setaccelmax)(iONode,int);
  int (*getaccelmin)(iONode);
  void (*setaccelmin)(iONode,int);
  Boolean (*isactive)(iONode);
  void (*setactive)(iONode,Boolean);
  int (*getaddr)(iONode);
  void (*setaddr)(iONode,int);
  Boolean (*isadjustaccel)(iONode);
  void (*setadjustaccel)(iONode,Boolean);
  int (*getbbtcorrection)(iONode);
  void (*setbbtcorrection)(iONode,int);
  Boolean (*isbbtevent)(iONode);
  void (*setbbtevent)(iONode,Boolean);
  int (*getbbtkey)(iONode);
  void (*setbbtkey)(iONode,int);
  int (*getbbtmaxdiff)(iONode);
  void (*setbbtmaxdiff)(iONode,int);
  int (*getbbtstartinterval)(iONode);
  void (*setbbtstartinterval)(iONode,int);
  int (*getbbtsteps)(iONode);
  void (*setbbtsteps)(iONode,int);
  const char* (*getblockenterid)(iONode);
  void (*setblockenterid)(iONode,const char*);
  Boolean (*isblockenterside)(iONode);
  void (*setblockenterside)(iONode,Boolean);
  const char* (*getblockid)(iONode);
  void (*setblockid)(iONode,const char*);
  int (*getblockwaittime)(iONode);
  void (*setblockwaittime)(iONode,int);
  int (*getbus)(iONode);
  void (*setbus)(iONode,int);
  const char* (*getcargo)(iONode);
  void (*setcargo)(iONode,const char*);
  const char* (*getcatnr)(iONode);
  void (*setcatnr)(iONode,const char*);
  Boolean (*ischeck2in)(iONode);
  void (*setcheck2in)(iONode,Boolean);
  const char* (*getclass)(iONode);
  void (*setclass)(iONode,const char*);
  const char* (*getcmd)(iONode);
  void (*setcmd)(iONode,const char*);
  int (*getcmdDelay)(iONode);
  void (*setcmdDelay)(iONode,int);
  Boolean (*iscommuter)(iONode);
  void (*setcommuter)(iONode,Boolean);
  const char* (*getconsist)(iONode);
  void (*setconsist)(iONode,const char*);
  Boolean (*isconsist_lightsoff)(iONode);
  void (*setconsist_lightsoff)(iONode,Boolean);
  Boolean (*isconsist_syncfun)(iONode);
  void (*setconsist_syncfun)(iONode,Boolean);
  int (*getconsist_syncfunmap)(iONode);
  void (*setconsist_syncfunmap)(iONode,int);
  Boolean (*isconsist_synclights)(iONode);
  void (*setconsist_synclights)(iONode,Boolean);
  Boolean (*isconsistcmd)(iONode);
  void (*setconsistcmd)(iONode,Boolean);
  int (*getdecelerate)(iONode);
  void (*setdecelerate)(iONode,int);
  const char* (*getdecfile)(iONode);
  void (*setdecfile)(iONode,const char*);
  const char* (*getdecimage)(iONode);
  void (*setdecimage)(iONode,const char*);
  const char* (*getdectype)(iONode);
  void (*setdectype)(iONode,const char*);
  const char* (*getdesc)(iONode);
  void (*setdesc)(iONode,const char*);
  const char* (*getdestblockid)(iONode);
  void (*setdestblockid)(iONode,const char*);
  Boolean (*isdir)(iONode);
  void (*setdir)(iONode,Boolean);
  int (*getdirpause)(iONode);
  void (*setdirpause)(iONode,int);
  const char* (*getdocu)(iONode);
  void (*setdocu)(iONode,const char*);
  const char* (*getengine)(iONode);
  void (*setengine)(iONode,const char*);
  int (*getent2incorr)(iONode);
  void (*setent2incorr)(iONode,int);
  int (*getera)(iONode);
  void (*setera)(iONode,int);
  int (*getevttimer)(iONode);
  void (*setevttimer)(iONode,int);
  Boolean (*isfifotop)(iONode);
  void (*setfifotop)(iONode,Boolean);
  Boolean (*isfn)(iONode);
  void (*setfn)(iONode,Boolean);
  int (*getfncnt)(iONode);
  void (*setfncnt)(iONode,int);
  Boolean (*isfreeblockonenter)(iONode);
  void (*setfreeblockonenter)(iONode,Boolean);
  int (*getfx)(iONode);
  void (*setfx)(iONode,int);
  const char* (*getid)(iONode);
  void (*setid)(iONode,const char*);
  const char* (*getidentifier)(iONode);
  void (*setidentifier)(iONode,const char*);
  Boolean (*isignorefn)(iONode);
  void (*setignorefn)(iONode,Boolean);
  const char* (*getiid)(iONode);
  void (*setiid)(iONode,const char*);
  const char* (*getimage)(iONode);
  void (*setimage)(iONode,const char*);
  int (*getimagenr)(iONode);
  void (*setimagenr)(iONode,int);
  Boolean (*isinatpre2in)(iONode);
  void (*setinatpre2in)(iONode,Boolean);
  Boolean (*isinfo4throttle)(iONode);
  void (*setinfo4throttle)(iONode,Boolean);
  const char* (*getlclib)(iONode);
  void (*setlclib)(iONode,const char*);
  int (*getlen)(iONode);
  void (*setlen)(iONode,int);
  Boolean (*ismanual)(iONode);
  void (*setmanual)(iONode,Boolean);
  Boolean (*ismanually)(iONode);
  void (*setmanually)(iONode,Boolean);
  int (*getmass)(iONode);
  void (*setmass)(iONode,int);
  int (*getmaxload)(iONode);
  void (*setmaxload)(iONode,int);
  int (*getmaxwaittime)(iONode);
  void (*setmaxwaittime)(iONode,int);
  long (*getmdate)(iONode);
  void (*setmdate)(iONode,long);
  int (*getmint)(iONode);
  void (*setmint)(iONode,int);
  const char* (*getmode)(iONode);
  void (*setmode)(iONode,const char*);
  const char* (*getmodereason)(iONode);
  void (*setmodereason)(iONode,const char*);
  long (*getmtime)(iONode);
  void (*setmtime)(iONode,long);
  int (*getnrcars)(iONode);
  void (*setnrcars)(iONode,int);
  const char* (*getnumber)(iONode);
  void (*setnumber)(iONode,const char*);
  const char* (*getoid)(iONode);
  void (*setoid)(iONode,const char*);
  Boolean (*isplacing)(iONode);
  void (*setplacing)(iONode,Boolean);
  int (*getport)(iONode);
  void (*setport)(iONode,int);
  const char* (*getprev_id)(iONode);
  void (*setprev_id)(iONode,const char*);
  int (*getpriority)(iONode);
  void (*setpriority)(iONode,int);
  const char* (*getprot)(iONode);
  void (*setprot)(iONode,const char*);
  int (*getprotver)(iONode);
  void (*setprotver)(iONode,int);
  const char* (*getpurchased)(iONode);
  void (*setpurchased)(iONode,const char*);
  Boolean (*isreducespeedatenter)(iONode);
  void (*setreducespeedatenter)(iONode,Boolean);
  Boolean (*isregulated)(iONode);
  void (*setregulated)(iONode,Boolean);
  const char* (*getremark)(iONode);
  void (*setremark)(iONode,const char*);
  Boolean (*isresetplacing)(iONode);
  void (*setresetplacing)(iONode,Boolean);
  Boolean (*isrestorefx)(iONode);
  void (*setrestorefx)(iONode,Boolean);
  Boolean (*isrestorefxalways)(iONode);
  void (*setrestorefxalways)(iONode,Boolean);
  Boolean (*isrestorespeed)(iONode);
  void (*setrestorespeed)(iONode,Boolean);
  Boolean (*isresumeauto)(iONode);
  void (*setresumeauto)(iONode,Boolean);
  const char* (*getroadname)(iONode);
  void (*setroadname)(iONode,const char*);
  Boolean (*isroaming)(iONode);
  void (*setroaming)(iONode,Boolean);
  long (*getruntime)(iONode);
  void (*setruntime)(iONode,long);
  const char* (*getscheduleid)(iONode);
  void (*setscheduleid)(iONode,const char*);
  int (*getscidx)(iONode);
  void (*setscidx)(iONode,int);
  int (*getsecaddr)(iONode);
  void (*setsecaddr)(iONode,int);
  Boolean (*issecondnextblock)(iONode);
  void (*setsecondnextblock)(iONode,Boolean);
  int (*getsecspcnt)(iONode);
  void (*setsecspcnt)(iONode,int);
  const char* (*getshortid)(iONode);
  void (*setshortid)(iONode,const char*);
  Boolean (*isshortin)(iONode);
  void (*setshortin)(iONode,Boolean);
  Boolean (*isshow)(iONode);
  void (*setshow)(iONode,Boolean);
  int (*getshuntingdiv)(iONode);
  void (*setshuntingdiv)(iONode,int);
  int (*getspcnt)(iONode);
  void (*setspcnt)(iONode,int);
  const char* (*getstartupscid)(iONode);
  void (*setstartupscid)(iONode,const char*);
  const char* (*getstartuptourid)(iONode);
  void (*setstartuptourid)(iONode,const char*);
  Boolean (*issw)(iONode);
  void (*setsw)(iONode,Boolean);
  int (*getswaptimer)(iONode);
  void (*setswaptimer)(iONode,int);
  const char* (*getthrottleid)(iONode);
  void (*setthrottleid)(iONode,const char*);
  int (*getthrottlenr)(iONode);
  void (*setthrottlenr)(iONode,int);
  const char* (*gettourid)(iONode);
  void (*settourid)(iONode,const char*);
  const char* (*gettrain)(iONode);
  void (*settrain)(iONode,const char*);
  int (*gettrainlen)(iONode);
  void (*settrainlen)(iONode,int);
  int (*gettrainweight)(iONode);
  void (*settrainweight)(iONode,int);
  const char* (*getttlib)(iONode);
  void (*setttlib)(iONode,const char*);
  Boolean (*isusebbt)(iONode);
  void (*setusebbt)(iONode,Boolean);
  Boolean (*isusedepartdelay)(iONode);
  void (*setusedepartdelay)(iONode,Boolean);
  Boolean (*isusemanualroutes)(iONode);
  void (*setusemanualroutes)(iONode,Boolean);
  Boolean (*isuseownwaittime)(iONode);
  void (*setuseownwaittime)(iONode,Boolean);
  Boolean (*isusescheduletime)(iONode);
  void (*setusescheduletime)(iONode,Boolean);
  Boolean (*isusesecaddr)(iONode);
  void (*setusesecaddr)(iONode,Boolean);
  Boolean (*isuseshortid)(iONode);
  void (*setuseshortid)(iONode,Boolean);
  Boolean (*isv0onswap)(iONode);
  void (*setv0onswap)(iONode,Boolean);
  const char* (*getvalue)(iONode);
  void (*setvalue)(iONode,const char*);
  iONode (*getfundef)(iONode);
  iONode (*nextfundef)(iONode,iONode);
  void (*setfundef)(iONode,iONode);
  iONode (*getcvbyte)(iONode);
  iONode (*nextcvbyte)(iONode,iONode);
  void (*setcvbyte)(iONode,iONode);
  iONode (*getactionctrl)(iONode);
  iONode (*nextactionctrl)(iONode,iONode);
  void (*setactionctrl)(iONode,iONode);
  iONode (*getbbt)(iONode);
  iONode (*nextbbt)(iONode,iONode);
  void (*setbbt)(iONode,iONode);
  iONode (*getsbt)(iONode);
  iONode (*nextsbt)(iONode,iONode);
  void (*setsbt)(iONode,iONode);
  Boolean (*dump)(iONode node);
};

extern struct __wLoc wLoc;

#ifdef __cplusplus
  }
#endif


#endif
